name: Unit Tests

on:
  push:
    paths:
    - 'lua/**'
    - 'test/**'
  pull_request:
    paths:
    - 'src/**'
    - 'test/**'
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Install luajit"
      run: |
        sudo apt install luajit

    - name: "Run Tests"
      run: |
        luajit test/main.lua
